config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'employees/profile', to: 'employees#profile'
  post 'employees/search', to: 'employees#search', as: :employee_search
  get 'holidays/approved/:id', to: 'holidays#approved', as: :holiday_approved
  get 'holidays/schedule', to: 'holidays#schedule', as: :holiday_schedule
  get 'holidays/queue', to: 'holidays#queue', as: :holiday_queue
  get 'news/list', to: 'news#list', as: :news_list
  
  # D: Route statisitics to default controller
  get 'statistics', to: 'default#statistics'
  get 'statistics/employee_join_by_year', to: 'default#employee_join_by_year', as: :chart_join_by_year
  get 'statistics/employee_by_year', to: 'default#employee_by_age', as: :chart_by_age
  
  resources :employees
  resources :holidays
  resources :news
  
  root to: "default#index"
  
end

app/models/holiday.rb
class Holiday < ActiveRecord::Base
  
  validates_presence_of :leave_date
  
  belongs_to :employee
  
end

app/controllers/holidays_controller.rb
class HolidaysController < ApplicationController
  before_action :set_holiday, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_filter :ensure_admin!, only: [:delete]

  # GET /holidays
  # GET /holidays.json
  def index
    @holidays = Holiday.where( :employee_id => current_user.employee_id )
  end

  # GET /holidays/1
  # GET /holidays/1.json
  def show
  end

  # GET /holidays/new
  def new
    @holiday = Holiday.new
  end

  # GET /holidays/1/edit
  def edit
  end
  
  # GET /holidays/schedule
  def schedule
    @holidays = Holiday.where(:approved => true)
  end
  
  # GET /holidays/schedule
  def queue
    @holidays = Holiday.where(:approved => false)
  end
  
  # PATCH/PUT /holidays/approved/1
  # PATCH/PUT /holidays/approved/1.json
  def approved
    respond_to do |format|
      holiday_update = Holiday.find( params[:id] )
      holiday_update.approved = !holiday_update.approved
      if holiday_update.save
        format.html { redirect_to holidays_path, notice: 'Holiday was successfully approved.' }
        format.json { render :show, status: :ok, location: @holiday }
      else
        format.html { redirect_to @holiday, notice: 'Failed to approve holiday' }
        format.json { render json: @holiday.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /holidays
  # POST /holidays.json
  def create
    @holiday = Holiday.new(holiday_params)
    
    # D: Force new holidays to belong_to current user
    @holiday.employee_id = current_user.employee_id

    respond_to do |format|
      if @holiday.save
        format.html { redirect_to @holiday, notice: 'Holiday was successfully created.' }
        format.json { render :show, status: :created, location: @holiday }
      else
        format.html { render :new }
        format.json { render json: @holiday.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /holidays/1
  # PATCH/PUT /holidays/1.json
  def update
    respond_to do |format|
      if @holiday.update(holiday_params)
        format.html { redirect_to @holiday, notice: 'Holiday was successfully updated.' }
        format.json { render :show, status: :ok, location: @holiday }
      else
        format.html { render :edit }
        format.json { render json: @holiday.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /holidays/1
  # DELETE /holidays/1.json
  def destroy
    @holiday.destroy
    respond_to do |format|
      format.html { redirect_to holidays_url, notice: 'Holiday was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  
    # Use callbacks to share common setup or constraints between actions.
    def set_holiday
      @holiday = Holiday.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def holiday_params
      params[:holiday]
        .permit(
          :id,
          :leave_date,
          :user_id,
          :approved
        )
    end
end

app/helpers/holidays_helper.rb
module HolidaysHelper
end

app/views/holidays/_form.html.erb
<%= form_for @holiday, layout: :basic do |f| %>
  <% if @holiday.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@holiday.errors.count, "error") %> prohibited this holiday from being saved:</h2>

      <ul>
      <% @holiday.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.date_field :leave_date %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/holidays/_list_holidays.erb
<table data-toggle="table" class="table table-fixed">
  <thead>
    <tr>
      <th>Approved</th>
      <th>Leave Date</th>
      <th>Created</th>
      <th>Updated</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @holidays.each do |holiday| %>
      <tr>
        <td><% if holiday.approved? %>Approved<% else %>Pending<% end %></td>
        <td><%= holiday.leave_date %></td>
        <td><%= holiday.created_at %></td>
        <td><%= holiday.updated_at %></td>
        <td>
          <% if current_user.admin? %>
            <%= link_to(icon(:ok), holiday_approved_path(holiday)) unless holiday.approved? %>
            <%= link_to(icon(:remove), holiday_approved_path(holiday)) if holiday.approved? %>
          <% end %>
        </td>
        <td><%= link_to icon(:search), holiday %></td>
        <td><%= link_to icon(:edit), edit_holiday_path(holiday) %></td>
        <td><%= link_to icon(:trash), holiday, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/holidays/edit.html.erb
<h1>Editing Holiday</h1>

<%= render 'form' %>

<%= link_to 'Show', @holiday %> |
<%= link_to 'Back', holidays_path %>

app/views/holidays/index.html.erb
<%= render 'employees/tab_control' %>
<%= render 'holidays/list_holidays' %>

<%= link_to "#{icon(:plus)} Add Holiday", new_holiday_path %>

app/views/holidays/new.html.erb
<%= render 'employees/tab_control' %>
<h1>New Holiday</h1>

<%= render 'form' %>

app/views/holidays/queue.html.erb
<%= render 'employees/employee_tab_control' %>
<%= render 'holidays/list_holidays' %>

app/views/holidays/schedule.html.erb
<%= render 'employees/employee_tab_control' %>
<%= render 'holidays/list_holidays' %>

app/views/holidays/show.html.erb
<%= render 'employees/tab_control' %>
<table data-toggle="table" class="table table-fixed">
  
  <tr>
    <td>User</td>
    <td><%= "#{@holiday.employee.sname}, #{@holiday.employee.fname}" if @holiday.employee %></td>
  </tr>
  
  <tr>
    <td>Leave Date</td>
    <td><%= @holiday.leave_date %></td>
  </tr>
  
  <tr>
    <td>Created</td>
    <td><%= @holiday.created_at %></td>
  </tr>
  
  <tr>
    <td>Updated</td>
    <td><%= @holiday.created_at %></td>
  </tr>
  
</table>
<%= link_to 'Edit', edit_holiday_path(@holiday) %> |
<%= link_to 'Back', holidays_path %>