config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'employees/profile', to: 'employees#profile'
  post 'employees/search', to: 'employees#search', as: :employee_search
  get 'holidays/approved/:id', to: 'holidays#approved', as: :holiday_approved
  get 'holidays/schedule', to: 'holidays#schedule', as: :holiday_schedule
  get 'holidays/queue', to: 'holidays#queue', as: :holiday_queue
  get 'news/list', to: 'news#list', as: :news_list
  
  # D: Route statisitics to default controller
  get 'statistics', to: 'default#statistics'
  get 'statistics/employee_join_by_year', to: 'default#employee_join_by_year', as: :chart_join_by_year
  get 'statistics/employee_by_year', to: 'default#employee_by_age', as: :chart_by_age
  
  resources :employees
  resources :holidays
  resources :news
  
  root to: "default#index"
  
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  
  # Validation
  validates_presence_of :fname
  validates_presence_of :sname
  validates_presence_of :dob
  validates_presence_of :join_date
  validates_presence_of :sex
  validates :salary, numericality: { only_integer: true }
  
  has_one :user
  has_many :holidays
  
  def self.search_name(query)
    where("concat(fname, ', ', sname) LIKE ?", "%#{query}%" )
  end

  # Group by year #{column} cast returned float to integer - bammm!  
  def self.group_by_year(column)
    group("EXTRACT(YEAR FROM #{column})::int")
  end
  
  # Group by age #{column} cast returned float to integer - bammm!  
  def self.workforce_age()
    group("date_part('year', age(dob))::int")
  end
  
  
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  
  before_action :set_employee, only: [:show, :edit, :update, :destroy, :profile]
  before_action :authenticate_user!
  before_filter :ensure_admin!, except: [:profile]
  
  # GET /employees
  # GET /employees.json
  def index
    #@employees = Employee.all
    @employees = Employee.paginate(:page => params[:page], :per_page => 10)
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end
  
  # POST /employee/search
  def search
    # D: Custom search method on model searches concatinated 
    # D: sname, fname for keyword like match
    @employees = Employee.paginate(:page => params[:page], :per_page => 10).search_name(params[:keywords])
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # GET /employees/profile
  def profile
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      # D: Use the provided param if set else default to current user id
      @employee = Employee.find(params[:id] || current_user.employee_id)
    end

    # Never trust parameters from the scary internet, 
    # only allow the white list through
    # D: So lame... rails explodes chickens when not white listed
    def employee_params
      params[:employee]
        .permit(
          :id, 
          :fname, 
          :sname, 
          :dob, 
          :salary, 
          :join_date,
          :end_date, 
          :sex,
          :keywords
        )
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_employee_tab_control.erb
<div class="row clearfix">
	<div class="col-md-12 column">
		<ul class="nav nav-tabs">
			<li>
				<a href="/employees">Employee list</a>
			</li>
			<li>
				<%= link_to "Holiday Schedule", holiday_schedule_path %>
			</li>
			<li>
				<%= link_to "Approval Queue", holiday_queue_path %>
			</li>
		</ul>
	</div>
</div>

app/views/employees/_form.html.erb
<%= form_for @employee, layout: :basic do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
         <%= f.text_field :fname, autocomplete: "off" %>
         <%= f.text_field :sname, autocomplete: "off" %>
         <%= f.date_field :sex %>
         <%= f.date_field :dob %>
         <%= f.date_field :join_date %>
         <%= f.number_field :salary %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/_tab_control.erb
<div class="row clearfix">
	<div class="col-md-12 column">
		<ul class="nav nav-tabs">
			<li>
				<a href="/employees/profile">Profile</a>
			</li>
			<li>
				<a href="/holidays">Holidays Report</a>
			</li>
		</ul>
	</div>
</div>

app/views/employees/edit.html.erb
<%= render 'tab_control' %>
<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<%= render 'employee_tab_control' %>
<%= will_paginate @employee, renderer: BootstrapPagination::Rails %>
<table data-toggle="table" class="table table-fixed">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Sur Name</th>
      <th>Sex</th>
      <th>Date of birth</th>
      <th>Join date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.fname %></td>
        <td><%= employee.sname %></td>
        <td><%= employee.sex %></td>
        <td><%= employee.dob %></td>
        <td><%= employee.join_date %></td>
        <td><%= link_to icon(:search), employee %></td>
        <td><%= link_to icon(:edit), edit_employee_path(employee) %></td>
        <td><%= link_to icon(:trash), employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "#{icon(:plus)} New Employee", new_employee_path %>

app/views/employees/new.html.erb
<%= render 'employee_tab_control' %>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/profile.erb
<%= render 'employees/tab_control' %>

<table class="table table-fixed">
  <tbody>
     <tr>
      <th colspan='2'>Email</th>
    </tr>
    <tr>
      <td colspan='2'><%= @employee.user.email || "Not available" %></td>
    </tr>
    <tr>
      <th>First Name</th>
      <th>Surname</th>
    </tr>
    <tr>
      <td><%= @employee.fname.titleize %></td>
      <td><%= @employee.sname.titleize %></td>
    </tr>
    <tr>
      <th>Sex</th>
      <th>Date of birth</th>
    </tr>
    <tr>
      <td><%= @employee.sex.titleize %></td>
      <td><%= @employee.dob %></td>
    </tr>
    <tr>
      <th>Join Date</th>
      <th>Finish Date</th>
    </tr>
    <tr>
      <td><%= @employee.join_date %></td>
      <td><%= @employee.end_date || "Not avaliable"%></td>
    </tr>
  </tbody>
  
</table>
<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/employees/search.html.erb
<%= render 'employee_tab_control' %>
<h1>Search Results</h1>
<%= will_paginate @employees, renderer: BootstrapPagination::Rails %>
<%= @params %>
<table data-toggle="table" class="table table-fixed">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Sur Name</th>
      <th>Sex</th>
      <th>Date of birth</th>
      <th>Join date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.fname %></td>
        <td><%= employee.sname %></td>
        <td><%= employee.sex %></td>
        <td><%= employee.dob %></td>
        <td><%= employee.join_date %></td>
        <td><%= link_to icon(:search), employee %></td>
        <td><%= link_to icon(:edit), edit_employee_path(employee) %></td>
        <td><%= link_to icon(:trash), employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "#{icon(:plus)} New Employee", new_employee_path %>

app/views/employees/show.html.erb
<%= render 'employee_tab_control' %>
<table class="table table-fixed">
  <tbody>
     <tr>
      <th colspan='2'>User ID</th>
    </tr>
    <tr>
      <td colspan='2'><%= @employee.user_id || "Not available" %></td>
    </tr>
    <tr>
      <th>First Name</th>
      <th>Surname</th>
    </tr>
    <tr>
      <td><%= @employee.fname.titleize %></td>
      <td><%= @employee.sname.titleize %></td>
    </tr>
    <tr>
      <th>Sex</th>
      <th>Date of birth</th>
    </tr>
    <tr>
      <td><%= @employee.sex.titleize %></td>
      <td><%= @employee.dob %></td>
    </tr>
    <tr>
      <th>Join Date</th>
      <th>Finish Date</th>
    </tr>
    <tr>
      <td><%= @employee.join_date %></td>
      <td><%= @employee.end_date || "Not avaliable"%></td>
    </tr>
  </tbody>
  
</table><%= @employee.fname %>
<%= @employee.sname %>
<%= @employee.dob %>
<%= @employee.sex %>
<%= @employee.join_date %>
<%= @employee.end_date %>
<%= @employee.user_id %>
<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>