config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'employees/profile', to: 'employees#profile'
  post 'employees/search', to: 'employees#search', as: :employee_search
  get 'holidays/approved/:id', to: 'holidays#approved', as: :holiday_approved
  get 'holidays/schedule', to: 'holidays#schedule', as: :holiday_schedule
  get 'holidays/queue', to: 'holidays#queue', as: :holiday_queue
  get 'news/list', to: 'news#list', as: :news_list
  
  # D: Route statisitics to default controller
  get 'statistics', to: 'default#statistics'
  get 'statistics/employee_join_by_year', to: 'default#employee_join_by_year', as: :chart_join_by_year
  get 'statistics/employee_by_year', to: 'default#employee_by_age', as: :chart_by_age
  
  resources :employees
  resources :holidays
  resources :news
  
  root to: "default#index"
  
end

app/controllers/default_controller.rb
class DefaultController < ApplicationController

    before_action :authenticate_user!, only: [:statistics, :employee_by_age, :employee_join_by_year]
    before_filter :ensure_admin!, only: [:statistics, :employee_by_age, :employee_join_by_year]

    def index
    end
    
    def statistics
    end
    
    def employee_join_by_year
       render json: Employee.group_by_year('join_date').count.chart_json 
    end
    
    def employee_by_age
       render json: Employee.workforce_age.count.chart_json 
    end
    
    
end

app/helpers/default_helper.rb
module DefaultHelper
end

app/views/default/index.html.erb
<div class="container page-header" ng-controller='NewsCtrl as news'>
	<div class="row clearfix">
		<div class="col-md-4 column" ng-repeat="(index, article) in news.news.articles">
			<h2>
				{{article.title}}
			</h2>
			<p>
				{{article.body | limitTo: 500 }}
			</p>
			<p>
				<a class="btn" href="/news/{{article.id}}">Read more »</a>
			</p>
		</div>
	</div>
</div>

app/views/default/statistics.html.erb
<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>

<div class='row'>
  
  <div class='col-xs-12'>
    <h2>Hire trend</h2>
    <%= bar_chart chart_join_by_year_path, discrete: true, library: { format: '0' } %>
  </div>
</div>
<div class='row'>  
  <div class='col-xs-12'>
    <h2>Workforce Age</h2>
    <%= area_chart chart_by_age_path, discrete: true, library: { format: '0' } %>
  </div>
</div>