config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'employees/profile', to: 'employees#profile'
  post 'employees/search', to: 'employees#search', as: :employee_search
  get 'holidays/approved/:id', to: 'holidays#approved', as: :holiday_approved
  get 'holidays/schedule', to: 'holidays#schedule', as: :holiday_schedule
  get 'holidays/queue', to: 'holidays#queue', as: :holiday_queue
  get 'news/list', to: 'news#list', as: :news_list
  
  # D: Route statisitics to default controller
  get 'statistics', to: 'default#statistics'
  get 'statistics/employee_join_by_year', to: 'default#employee_join_by_year', as: :chart_join_by_year
  get 'statistics/employee_by_year', to: 'default#employee_by_age', as: :chart_by_age
  
  resources :employees
  resources :holidays
  resources :news
  
  root to: "default#index"
  
end

app/models/news.rb
class News < ActiveRecord::Base
  
  validates_presence_of :title
  validates_presence_of :body
  
  belongs_to :employee
  
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :list]
  before_filter :ensure_admin!, except: [:show, :list]

  # GET /news
  # GET /news.json
  def index
    @news = News.paginate(:page => params[:page], :per_page => 10)
  end
  
  # GET /news/list.json
  def list
    @news = News.last( 3 ).reverse
    respond_to do |format|
      format.json { render json: @news }
    end
  end
  

  # GET /news/1
  # GET /news/1.json
  def show
  end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_index_url, notice: 'News was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params[:news]
        .permit(
          :title,
          :body,
          :published
        )
    end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_form.html.erb
<%= form_for @news,  layout: :basic  do |f| %>
  <% if @news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
      <% @news.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
        <%= f.text_field :title, autocomplete: "off" %>
        <%= f.text_area :body, autocomplete: "off" %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/news/_news_tab_control.erb
<% if user_signed_in? %>
  <% if current_user.admin? %>

		<div class="row clearfix">
			<div class="col-md-12 column">
				<ul class="nav nav-tabs">
					<li>
						<%= link_to "New Article", new_news_path %>
					</li>
					<li>
						<%= link_to "List Articles", news_index_path %>
					</li>
					<li>
						
					</li>
				</ul>
			</div>
		</div>
		
  <% end %>
<% end %>

app/views/news/edit.html.erb
<h1>Editing News</h1>

<%= render 'form' %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_index_path %>

app/views/news/index.html.erb
<%= render 'news_tab_control' %>

<h1>News Articles</h1>


<%= will_paginate @news, renderer: BootstrapPagination::Rails %>
<table data-toggle="table" class="table table-fixed">
  <thead>
    <tr>
      <th>Title</th>
      <th>Word count</th>
      <th>Created</th>
      <th>Updated</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @news.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.body.scan(/\w+/).size %></td>
        <td><%= article.created_at %></td>
        <td><%= article.updated_at %></td>
        <td><%= link_to icon(:search), article %></td>
        <td><%= link_to icon(:edit), edit_news_path(article) %></td>
        <td><%= link_to icon(:trash), article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/news/new.html.erb
<%= render 'news_tab_control' %>
<h1>New news article</h1>
<%= render 'form' %>

<%= link_to 'Back', news_index_path %>

app/views/news/show.html.erb
<%= render 'news_tab_control' %>

<h1><%= @news.title %></h1>
<div id='container'>
  <%= @news.body %>
</div>
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <%= link_to 'Edit', edit_news_path(@news) %> |
    <%= link_to 'Back', news_index_path %>
  <% end %>
<% end %>